version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    container_name: dns
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: